<?php
$value = array (
  'wwwprefix' => 'http://pidai8.com',
  'imgprefix' => 'http://pidai8.com',
  'cssprefix' => 'http://pidai8.com',
  'sitename' => '皮带',
  'sitetitle' => '精品皮带',
  'abbreviation' => '皮带',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'description' => '比牛皮还牛的皮带',
  'keywords' => '皮带',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'googlemap' => '',
  'indexteam' => '6',
  'sideteam' => '0',
);
?>